org: gabrielber96
app: reto-back
service: aws-node-express-api-project

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: sa-east-1
  apiGateway:
    shouldStartNameWithService: true
plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
